### ISSUE TITLE
Status becomes 'unhealthy'

### ISSUE THREAD

**Issue by svengato** [legumeinfo/graphql-server#28]
I am now running graphql-server using
`sudo docker compose -f compose.yml -f compose.prod.yml up -d`
on both dev-pb-jekyll (PeanutBase VM) and wolfburn (desktop). The container status becomes "unhealthy" after startup in both cases. Should I really use compose.dev.yml instead? I will try that.

**Comment by svengato** [comment]
> Should I really use compose.dev.yml instead?

This did not work (tried on wolfburn).

**Comment by alancleary** [comment]
Currently dev and prod run just fine on my computer; there's no information here to help me replicate or track down the cause of the issue. What's the output of `docker logs`? Did you make any local changes? Did you do a clean build of the Docker image after pulling changes from GitHub and/or making local changes? What solutions have you already tried?

**Comment by svengato** [comment]
The container built and ran, but when I gave it a curl request (a test that worked before) it output
`curl: (56) Recv failure: Connection reset by peer`

Maybe I did not do a clean build, I will try again and check the log file.

**Comment by svengato** [comment]
`docker logs <container>` says:
```
6:09:19 PM - Starting compilation in watch mode...


6:09:21 PM - Found 0 errors. Watching for file changes.

> legumeinfo-graphql-server@1.0.0 serve
> node ./dist/index.js

file:///app/node_modules/@graphql-tools/schema/esm/addResolversToSchema.js:21
            throw new Error(`"${typeName}" defined in resolvers, but not in schema`);
                  ^

Error: "Query" defined in resolvers, but not in schema
    at addResolversToSchema (file:///app/node_modules/@graphql-tools/schema/esm/addResolversToSchema.js:21:19)
    at makeExecutableSchema (file:///app/node_modules/@graphql-tools/schema/esm/makeExecutableSchema.js:73:14)
    at ApolloServer.constructSchema (file:///app/node_modules/@apollo/server/dist/esm/ApolloServer.js:297:16)
    at new ApolloServer (file:///app/node_modules/@apollo/server/dist/esm/ApolloServer.js:68:49)
    at file:///app/dist/index.js:14:16
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.7.0
```

**Comment by sammyjava** [comment]
That's weird. I'm not getting that error on main in non-docker mode. It runs fine free of errors.

**Comment by alancleary** [comment]
> Error: "Query" defined in resolvers, but not in schema

This is helpful. The schema is defined in the `src/types/*.graphql` files. The JavaScript representation of the schema is generated from these files at run-time. This means these files need to be copied from the `src/` (TypeScript) directory into the `dist/` (JavaScript) directory as part of the build process. But TypeScript doesn't do this for us because `.graphql` files are not TypeScript files. [The `build` script handles this](https://github.com/legumeinfo/graphql-server/blob/main/package.json#L8) and [the updated `Dockerfile` explicitly runs this script](https://github.com/legumeinfo/graphql-server/blob/main/Dockerfile#L17), so odds are you haven't actually rebuilt the Docker image. Do so as follows:
```console
docker compose -f compose.yml -f compose.(dev|prod).yml up -d --build --force-recreate
```

**Comment by svengato** [comment]
I tried that, but still see the same problem (for compose.dev.yml).

**Comment by alancleary** [comment]
Have you tried running the service locally to determine whether it's a docker issue or something more general? Also, have you tried running a fresh copy of the repo to ensure it's a legitimate bug and not a side effect of something you've changed, e.g. in issue #27 you stated that you renamed docker compose services?

**Comment by svengato** [comment]
This is running locally on wolfburn.

**Comment by alancleary** [comment]
> Have you tried running the service locally to determine whether it's a docker issue or something more general?

> This is running locally on wolfburn. (No renaming was required.)

I meant "locally" as [just described by @sammyjava](https://github.com/legumeinfo/graphql-server/issues/28#issuecomment-1442244098) and as [described in the readme](https://github.com/legumeinfo/graphql-server#local).

**Comment by svengato** [comment]
Ah, _that_ "locally". That does not work at all, the `npm` commands cause permission-related errors.

**Comment by adf-ncgr** [comment]
let's try to get this figured out without the divine intervention of @alancleary who needs to be ready for his workshop next week. If we haven't solved it by then, we can prepare a hecatomb. I'll have a look at the dev-pb-jekyll instance

**Comment by adf-ncgr** [comment]
other than the claim of docker ps that it is "unhealthy", things seem to be working. Can you elaborate on what the test was that caused concern? Not %100 sure but I think the healthcheck itself may be broken.

**Comment by adf-ncgr** [comment]
To clarify my last comment, I tried invoking the command representing the healthcheck and it seems curl is not found in the container. See https://stackoverflow.com/questions/64300599/why-do-i-get-curl-not-found-inside-my-nodealpine-docker-container for solution.

**Comment by adf-ncgr** [comment]
That may have worked, although I think the healthcheck curl command may also be misformed. Instead of:
`curl f --request POST ...`
I suspect it should be
`curl -f --request POST`

however, the service seems to be blissfully unconcerned about it so far. I'll PR the changes to the Dockerfile for wiser heads to review.

**Comment by svengato** [comment]
> other than the claim of docker ps that it is "unhealthy", things seem to be working.

Correct, at least the production version.

**Comment by alancleary** [comment]
FYI the healthcheck is [explicitly disabled](https://github.com/legumeinfo/graphql-server/blob/main/compose.dev.yml#L5) in the dev compose file so I'm not sure what the issue may be there.

**Comment by svengato** [comment]
I will look at 'dev' issues again today. I set it back to 'prod' on PeanutBase, and so far (due to Andrew's modification?) it is still healthy.

**Comment by svengato** [comment]
If I comment out the 'volumes' section of compose.dev.yml, the dev version works. Is there any reason we need that? The prod version does not have one.

**Comment by alancleary** [comment]
> If I comment out the 'volumes' section of compose.dev.yml, the dev version works. Is there any reason we need that? The prod version does not have one.

The dev file is for development so it mounts files from the copy of the repository on the host machine so you can edit them on the host using your IDE of choice. Prod doesn't do this because you shouldn't be editing the server in production. If you're OK with commenting out the volume lines in the dev file then you should probably be using prod in the first place...

This suggests to me that there's something in your copy of the repo that is being mounted in the container volume that's causing problems. This shouldn't be the case if you're running a clean clone of the repo, as I suggested before... I defer further debugging to @adf-ncgr and am unsubscribing from this thread. Godspeed!

**Comment by svengato** [comment]
> This shouldn't be the case if you're running a clean clone of the repo, as I suggested before

I forgot that part. After trashing the old repository, making a clean clone, and doing a local build, I get the same error.
```
npm install
npm run serve:dev
```
```
11:17:44 AM - Starting compilation in watch mode...


11:17:46 AM - Found 0 errors. Watching for file changes.

> legumeinfo-graphql-server@1.0.0 serve
> node ./dist/index.js

file:///home/sgr/Code/legumeinfo/graphql-server/node_modules/@graphql-tools/schema/esm/addResolversToSchema.js:21
            throw new Error(`"${typeName}" defined in resolvers, but not in schema`);
                  ^

Error: "Query" defined in resolvers, but not in schema
    at addResolversToSchema (file:///home/sgr/Code/legumeinfo/graphql-server/node_modules/@graphql-tools/schema/esm/addResolversToSchema.js:21:19)
    at makeExecutableSchema (file:///home/sgr/Code/legumeinfo/graphql-server/node_modules/@graphql-tools/schema/esm/makeExecutableSchema.js:73:14)
    at ApolloServer.constructSchema (file:///home/sgr/Code/legumeinfo/graphql-server/node_modules/@apollo/server/dist/esm/ApolloServer.js:297:16)
    at new ApolloServer (file:///home/sgr/Code/legumeinfo/graphql-server/node_modules/@apollo/server/dist/esm/ApolloServer.js:68:49)
    at file:///home/sgr/Code/legumeinfo/graphql-server/dist/index.js:14:16
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1
```

**Comment by svengato** [comment]
Noticed a cryptic comment in `src/resolvers/intermine/index.ts`:
```
// TODO: our resolver type returned by the factories doesn't match the type
// expected by mergeResolvers
```
Not sure whether this has anything to do with the problem.

**Comment by adf-ncgr** [comment]
No, I think you just need to:
`npm install
npm run build
npm run serve:dev`
not sure why the README omits the build step for the dev but it seems to be needed, as perhaps suggested earlier in the thread
https://github.com/legumeinfo/graphql-server/issues/28#issuecomment-1442366668

**Comment by svengato** [comment]
That makes sense, I had not run `npm run build` before `npm run serve:dev`. Now this local version works (on wolfburn) for both dev and prod.

Also tried running graphql-server with 'docker compose'. Both dev and prod versions work (still on wolfburn).

Next: repeat for PeanutBase. But which should we run there, dev or prod?
