### ISSUE TITLE
Add linkout service to GraphQL API

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#31]
@adf-ncgr has implemented a [linkout microservice](https://github.com/legumeinfo/microservices/tree/main/linkouts) that we would like to start integrating into the LIS Jekyll site via web components. For uniformity, we would like the web components to call the service via the GraphQL API, thus the microservice needs to be added to the GraphQL API and corresponding resolvers and data sources need to be implemented.

**Comment by alancleary** [comment]
That all sounds good.

**Comment by sammyjava** [comment]
OK, stop me before I drown in the deep end. I'm presuming that I build out the microservices (which gene and genomic region linkouts are part of) with the same layout that you built intermine. That is:
```
data-sources/
├── index.ts
├── intermine
│   ├── api
│   │   ├── get-authors.ts
│   │   ├── ...
│   │   ├── index.ts
│   │   ├── pagination.ts
│   │   ├── search-expression-samples.ts
│   │   ├── ...
│   │   └── search-traits.ts
│   ├── index.ts
│   ├── intermine.server.ts
│   └── models
│       ├── annotatable.ts
│   │   ├── ...
│       ├── index.ts
│   │   ├── ...
│       └── trait.ts
└── microservices
│   ├── api
│   │   ├── get-gene-linkouts.ts
│   │   ├── get-location-linkouts.ts
│   │   ├── ...
│   │   ├── index.ts
│   │   ├── pagination.ts
    ├── index.ts
    ├── microservices.server.ts
    └── models
        ├── index.ts
        └── linkout.ts
```
I don't see the need for a standalone Linkout resolver since it doesn't have any identifier or queryable thing. One only gets linkouts as Gene.linkouts (in the Gene resolver) and Location.linkouts (in the Location resolver, which exists because it has an ID in the mine). So as far as resolvers go, I only see adding 
```
        linkouts: async (gene, _, { dataSources }) => {
            return dataSources[sourceName].getGeneLinkouts(gene);
        },
```
to gene.ts and 
```
        linkouts: async (location, _, { dataSources }) => {
            return dataSources[sourceName].getLocationLinkouts(location);
        },
```
to location.ts.

**Comment by alancleary** [comment]
Nah. The microservices are much simpler than Intermine so breaking all the request functions into separate files and gluing them together with a mixin is complete overkill. A single file with a class that extends the `RESTDataSource` class should be sufficient:
```
data-sources/
├── index.ts
├── intermine
│   └── ...
└── microservices
    ├── index.ts
    └── microservices.server.ts
```
The class should still use models, though. They'll just be in the `microservices.server.ts` file with the class.

**Comment by sammyjava** [comment]
Glad I asked! :) Will do.

**Comment by sammyjava** [comment]
I give up. My brain just doesn't follow this code structure. All yours. :)

**Comment by alancleary** [comment]
Done in PR #37.
