### ISSUE TITLE
Need support for OR constraints in path queries

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#32]
In updating the gene search API, I realized that we do not support OR constraints. The use case is that the user enters a string which is matched against either the Gene.primaryIdentifier or the Gene.name, which sometimes is totally different from the primaryIdentifier. 

Example:
| primaryIdentifier | name |
| --- | --- | 
| glyma.Hwangkeum.gnm1.ann1.GmHk_13G038699 | HSP70_11 |

The appropriate path query looks like this, with the **constraintLogic** and indentifying **code** attributes:
```xml
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.name" longDescription="" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A or B">
  <constraint path="Gene.primaryIdentifier" code="A" op="CONTAINS" value="HSP70_11"/>
  <constraint path="Gene.name" code="B" op="CONTAINS" value="HSP70_11"/>
</query>
```

@cann0010 and @adf-ncgr : an alternative would be to bail on the "name or identifier" search parameter and have separate name and identifier fields in the gene search UI. This might be confusing to people that have no idea what the difference is. But we can certainly do it that way in the near term.

This is in reference to intermine.server.ts:interminePathQuery.

**Comment by adf-ncgr** [comment]
Thanks @sammyjava- the example you gave is probably extreme ("totally different from the primaryIdentifier"), but does the same issue apply if we want one field that supports entering either primary or secondary identifier (ie full yuck or yuck-less id)- I am guessing that our saving grace in that case is that we can use CONTAINS. But I don't think we need to worry too much about "names" that aren't identifiers for the time being, since most Names (in gff) are just going to be secondary ids. Just my 2c, but probably if and when we start doing a better job of associating "biology names" with gene models I will reinvest.

**Comment by alancleary** [comment]
I think adding an optional `constraintLogic` parameter to the [`interminePathQuery` function](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/intermine.server.ts#L79) you mentioned and then implementing logic on a per endpoint basis (e.g. [`searchGenes`](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/api/search-genes.ts#L18)) would be sufficient. Note that the `constraintLogic` parameter would require adding an optional `code` parameter to the [`intermineConstraint` function](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/intermine.server.ts#L72) as well.

**Comment by sammyjava** [comment]
No, secondaryIdentifier is a substring of primaryIdentifier so it will always match a primaryIdentifier. I think this is only an "extreme case" because we're not providing gene names very often. Almost every Arabidopsis gene has a function-determined name (or symbol, if you will) different from ATnGnnnnn.

These both use CONTAINS. The problem is the OR to or-wise match two different fields. Right now I'm just coding a CONTAINS against primaryIdentifier and we can decide if we want to support the name field.

FWIW, here are the accessions for which name is NOT a substring of primaryIdentifier, typically because of extra Cajan. type prefixes.
```
       species         |  strain  
-----------------------+--------------
 Cajanus cajan         | ICPL87119
 Cicer arietinum       | CDCFrontier
 Cicer arietinum       | ICC4958
 Glycine max           | Hwangkeum
 Lens culinaris        | CDC_Redberry
 Lupinus albus         | Amiga
 Lupinus angustifolius | Tanjil
 Medicago truncatula   | HM004
 Medicago truncatula   | HM010
 Medicago truncatula   | HM022
 Medicago truncatula   | HM023
 Medicago truncatula   | HM034
 Medicago truncatula   | HM050
 Medicago truncatula   | HM056
 Medicago truncatula   | HM058
 Medicago truncatula   | HM060
 Medicago truncatula   | HM095
 Medicago truncatula   | HM125
 Medicago truncatula   | HM129
 Medicago truncatula   | HM185
 Medicago truncatula   | HM324
 Medicago truncatula   | R108
 Trifolium pratense    | MilvusB
 Vigna unguiculata     | IT97K-499-35
```

**Comment by sammyjava** [comment]
> I think adding an optional `constraintLogic` parameter to the [`interminePathQuery` function](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/intermine.server.ts#L79) you mentioned and then implementing logic on a per endpoint basis (e.g. [`searchGenes`](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/api/search-genes.ts#L18)) would be sufficient. Note that the `constraintLogic` parameter would require adding an optional `code` parameter to the [`intermineConstraint` function](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/intermine.server.ts#L72) as well.

I think I'll pass on implementing that.

**Comment by cann0010** [comment]
I am not sure I am following this correctly, but I wonder if the "identifier field" could be handled as a separate keyword search ... which could be used to find genes via their gene symbols (when available)? I expect it will be fairly common for a biologist to enter "LHY" or "Tfl1" or "Dt1" and hope to find genes in their selected species.

**Comment by adf-ncgr** [comment]
Thanks @cann0010 I agree this will be common but not sure we currently have the data to support getting good results. Try a keyword search in LegumeMine for any of those symbols and you will likely be dismayed. I think you have recently begun putting data that will be useful for this into https://github.com/legumeinfo/gene-function-registry so it will probably become more relevant soon. But I think the experiment of putting these symbols into the keyword search suggests that when the time comes we should make this a separate field than identifier (license plate gene naming tends to create a lot of false positives to gene symbols when "CONTAINS" is used)

**Comment by sammyjava** [comment]
Which is fine, and we can have rollovers providing examples to clarify that one field is for a license plate, the other is for a traditional gene symbol.

**Comment by alancleary** [comment]
This was done when we added support for join queries; see PR #90. Closing.
