### ISSUE TITLE
Changing the mine (or microservices URI) in deployment changes a repo file

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#42]
We should keep the mine and probably other URIs out of the repo, since when I put the code on dev-jekyll, etc. I have to change a repo file (minimine->legumemine). That breaks pulls, of course. I think the .env file is an appropriate place to list the mine, microservices, other deployment-specific data.

**Comment by svengato** [comment]
I agree, this would be useful for PeanutBase which uses ArachisMine instead of the default MiniMine.

**Comment by alancleary** [comment]
Note to self: This will require updating the section about the `.env` file in `README.md`. This change should also update the section to no longer state that the `.env` file is included in the repo.

**Comment by alancleary** [comment]
Done in PR #57.
