### ISSUE TITLE
Wherefore the production graphql-server?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#45]
We're nearing promotion of the gene search component to production, which means we need a production graphql server. Has this already been envisioned? Obviously I can stand one up on graphql.lis.ncgr.org:4000 (or whatever) but I think @alancleary had fancier methods in mind for deployment.

**Comment by alancleary** [comment]
I'm not sure what you mean by "envisioned" but everything is already in place to run the server in production mode with npm, docker, or docker compose. It's up to whoever is going to take ownership of the deployment to decide which method to use, proxying, domain, etc.

Regardless of what method is used, I would like to put automated docker image building and publishing in place, like what GCV and the microservices are doing. Then using docker (compose) is as simple as pulling the pre-built image from the GitHub Container Registry.

**Comment by sammyjava** [comment]
I'm talking about actually putting a graphql-server in production. Take ownership of that, please, along with the Docker stuff you'd like to use.

**Comment by adf-ncgr** [comment]
FWIW, I don't think @alancleary should be tasked with actual deployment, but I could take that on if you both like.

**Comment by alancleary** [comment]
> FWIW, I don't think @alancleary should be tasked with actual deployment, but I could take that on if you both like.

I was about to say the same thing. I don't want to dump it on you, though, so I was going to suggest you show me how you're deploying microservices and then I would automate it: new release tag -> automatically update deployment.

**Comment by sammyjava** [comment]
I'll let you two battle it out. :)

**Comment by sammyjava** [comment]
Plus, Alan has to deal with #43 since I bailed on it. :)

**Comment by adf-ncgr** [comment]
sounds good. my deployment strategies are not very slick; sounds like by volunteering I am likely to get upgraded by the @alancleary -bot

**Comment by alancleary** [comment]
My opinions aren't strong but I would think of the GraphQL server more as an API than a service. So either https://graphql.lis.ncgr.org or something similar to the services URL but for APIs, like https://api.lis.ncgr.org/graphql. I have no idea what else might be served on that subdomain!

**Comment by sammyjava** [comment]
Yeah, I don't care as long as it's on a constant, production hostname. It's under the hood, so I don't think having a human-remember-able hostname matters much. I think services.lis.ncgr.org/graphql is fine, and helps reduce hostname and Apache config bloat.

**Comment by adf-ncgr** [comment]
Hmm, I don't really understand the API vs services distinction. Isn't an API basically a collection of services? Not that any of us really care (but of course we somehow still manage not to converge on a single option!). @alancleary regardless of what the chosen endpoint name is, do you want someone (ie you or me) to tackle doing release-oriented things before engaging in deployment-oriented motions?

**Comment by sammyjava** [comment]
Oh, and thanks for that API/services explanation. But I still think of `graphql:4000/` as being a service, albeit implementing an API. And @adf-ncgr is mounting that "service" somewhere to accept requests.

**Comment by adf-ncgr** [comment]
By "release-oriented things" here I did mean the tag-based building of images to the registry and creation of release bundles (or whatever you call those tarballs you grab instead of cloning the repo). But having the pagination functionality certainly precedes that.

**Comment by alancleary** [comment]
I realized I never responded to your offer @adf-ncgr. This repo only needs the automated docker image building and publication. Feel free to handle that. You could more or less copy what the microservice repo is doing.

**Comment by adf-ncgr** [comment]
> Oh, and thanks for that API/services explanation. But I still think of `graphql:4000/` as being a service, albeit implementing an API. And @adf-ncgr is mounting that "service" somewhere to accept requests. I don't think one mounts an API.

not sure we ever came to consensus on what URL we want to point things to for the graphql service/API (despite us all avowing how little we really care about it). But unless anyone really cares, I'll go with [graphql.lis.ncgr.org](https://graphql.lis.ncgr.org)https://graphql.lis.ncgr.org/ which seems to be the approximate thing we can all live with (I can't live with runtime-for-fulfilling-api-queries.lis.ncgr.org !)

**Comment by alancleary** [comment]
> > Oh, and thanks for that API/services explanation. But I still think of `graphql:4000/` as being a service, albeit implementing an API. And @adf-ncgr is mounting that "service" somewhere to accept requests. I don't think one mounts an API.
> 
> not sure we ever came to consensus on what URL we want to point things to for the graphql service/API (despite us all avowing how little we really care about it). But unless anyone really cares, I'll go with [graphql.lis.ncgr.org](https://graphql.lis.ncgr.org) which seems to be the approximate thing we can all live with (I can't live with runtime-for-fulfilling-api-queries.lis.ncgr.org !)

Works for me!
