### ISSUE TITLE
Implement Annotatable, BioEntity, and SequenceFeature types

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#48]
As [discussed](https://github.com/legumeinfo/graphql-server/issues/43#issuecomment-1601677792) in issue #43, InterMine types that are an Annotatable, BioEntity, or SequenceFeature should also be those types in the GraphQL API. The point of this issue is to make sure the GraphQL implementation achieves this type parity. I'll also note that this will require implementing a lot of subfields that use the exact same code. Extra credit if this code is encapsulated in subfield factories that can be reused!

**Comment by sammyjava** [comment]
*goes out and smokes a cigarette with the other greasers instead of staying in the classroom for extra credit...* :)

**Comment by alancleary** [comment]
Addressing API inconsistencies for #43 got me 95% done with this issue so a went ahead and finished the last 5%. Done in commit 05c8ae0f192b6a280dafaede80ea5aca601edb66.
