### ISSUE TITLE
Resolve ambiguity by using Gene.primaryIdentifier instead of Gene.name

### ISSUE THREAD

**Issue by svengato** [legumeinfo/graphql-server#5]
Discussion from yesterday, related to the PeanutBase Jekyll site gene keyword search (but really a graphql-server issue?).

Sudhansu:

> I searched with key word 'starch' and it listed all genes aradu/araip/arahy with description containing 'starch'. Perfect, once the pagination issue is smoothed.
> However in this search there are two genes with the same name but different internal ids:
> G9KDZS    starch synthase 2/amyloplastic protein  (https://lis.ncgr.org/arachismine/report.do?id=17385692)
> G9KDZS    starch synthase 2/amyloplastic protein (https://lis.ncgr.org/arachismine/report.do?id=75483228)

Andrew:

> Those actually link to different versions (gnm1.ann1 and gnm2.ann1) of the same gene model.

Sam:

> One should NEVER use the short name of a gene to identify a unique gene. It is not a unique identifier.

We could distinguish these by using primaryIdentifier instead of name in the Gene object.

**Comment by sammyjava** [comment]
This is addressed, formerly, by using Object.id across the board, and in the new **use-identifiers-5.1.0.2** branch which queries by unique identifier. (That will be followed by a minor update to handle 5.1.0.3 data model changes that add primaryIdentifier to three other objects, plus fixing Phylonode.identifier to be unique.)
