### ISSUE TITLE
Implement extensible InterMine data-source attributes

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#50]
A handful of the InterMine models have the same attributes, i.e. the annotatable, bio entity, and sequence feature models. Similarly, some models redefine types relative to their type, i.e. data sets. We should implement stand-alone attribute arrays that encapsulate these common attributes so that all models that use them will be consistent and attributes we're currently not pulling into the GraphQL API can be easily added in the future.

- [x] Annotatable
- [x] BioEntity
- [x] DataSet
- [x] SequenceFeature
- [x] Transcript

**Comment by sammyjava** [comment]
Yeah, I had no idea how to do that. It'd be nice if GraphQL provided that, like Java - if you implement a Type you get that Type's attributes. All you get is a check that the attributes are present (which is good).

**Comment by alancleary** [comment]
> Yeah, I had no idea how to do that. It'd be nice if GraphQL provided that, like Java - if you implement a Type you get that Type's attributes. Right now all you get is a check that the attributes are present (which is good).

I'm talking about the lists of model attributes that we're requesting from InterMine that we have to code by hand. A lot of them are redundant so encapsulating the redundant bits in reusable lists would be nice.

As for GraphQL models, there's code generation tools we can use to generate TypeScript types from our GraphQL files, which I intend to introduce in the future.

**Comment by sammyjava** [comment]
Ah, gotcha. Yeah, most stuff is at least Annotatable if not BioEntity or SequenceFeature. On the mine side you never deal with those, the extend takes care of it, so nice to do same with our GraphQL model defs.

**Comment by alancleary** [comment]
Done via issue #112.
