### ISSUE TITLE
Please test 5.1.0.3-model-changes

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#54]
This isn't ready for a merge to main yet because we're still on 5.1.0.2 for production and other development. BUT, the dev MiniMine is on 5.1.0.3 so it'd be nice if you could give this a test with a beer in hand some time.

5.1.0.3 is now frozen as I've got major builds running. The changes have to do with:
- GenotypingPlatform is a new Annotatable object. 
- GeneticMarker now has a genotypingPlatforms collection (not an single string attribute)
- PanGeneSet is a new Annotatable object which has genes and proteins collections
- GWASResult is now an Annotatable
- LinkageGroup is now an Annotatable
- QTL is now an Annotatable
- GeneticMap has a genotypingPlatform reference
- GWAS has a genotypingPlatform reference

**Comment by sammyjava** [comment]
I've updated this branch from the latest main. @That-Thing this should work well against the dev MiniMine 5.1.0.3 which contains pan-gene sets as well as Newick for @rispop .
```
INTERMINE_URI=https://mines.dev.lis.ncgr.org/minimine/service
```

**Comment by alancleary** [comment]
I (finally) had a look at the branch. It look pretty good overall. Can you open a PR so I can add notes while reviewing the code and testing?

**Comment by alancleary** [comment]
Done.
