### ISSUE TITLE
Traits query is crashing against GlycineMine

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#75]
From @That-Thing 

_I tried running the graphql server with glycinemine, and found that running the traits query seems to somehow be crashing the mine itself._ 

I think we hit this a few weeks ago. Test, analyze, fix.

**Comment by alancleary** [comment]
@sammyjava @That-Thing Can you provide an example query that causes the error?

**Comment by That-Thing** [comment]
``` graphql
query Traits($name: String, $start: Int, $pageSize: Int) {
    traits(name: $name, page: $start, pageSize: $pageSize) { 
      results {
        name
        qtlStudy {
          identifier
          synopsis
          description
          genotypes
          organism {
            genus
            species
          }
          dataSet {
            publication {
              firstAuthor
              pubMedId
              doi
            }
          }
        }
        gwas {
          identifier
          synopsis
          description
          genotypes
          organism {
            genus
            species
          }
          dataSet {
            publication {
              firstAuthor
              pubMedId
              doi
            }
          }
        }
      }
      pageInfo {
        currentPage
        pageSize
        numResults
        pageCount
        hasPreviousPage
        hasNextPage
      }
    }
  }
  ```

**Comment by alancleary** [comment]
@That-Thing Can you confirm what values are being passed for the `$start` and `$pageSize` variables?

**Comment by That-Thing** [comment]
```json
{
  "name": "*",
  "page": 0,
  "pageSize": 10
}
```

**Comment by sammyjava** [comment]
Ahhh. Alan coded the pagination to use "page-based" numbering, meaning the first page is 1. page=0 throws an error. See here:

https://github.com/legumeinfo/graphql-server/blob/8f1d1f7656fdf9da42115b4af88cbdd1007e5827/src/data-sources/intermine/intermine.server.ts#L29

**Comment by sammyjava** [comment]
Also, name="*" isn't really a thing. Just leave name off of the input parameters. This works:
```json
{
  "page": 1,
  "pageSize": 10,
}
```
at least as far as I can tell.

**Comment by sammyjava** [comment]
HOWEVER I'm looking at my trait search component implemented here:

https://github.com/legumeinfo/web-components/blob/main/dev/lis-trait-search-element.html

and we do seem to have GlycineMine hanging on a search on "flower". So I'll continue to investigate. This is also true in Apollo Sandbox. There is definitely something crashy going on, and the mine throws `java.lang.IllegalArgumentException: Cannot find a query` but eventually recovers.

Continuing research....

**Comment by sammyjava** [comment]
> HOWEVER I'm looking at my trait search component implemented here:
> 
> https://github.com/legumeinfo/web-components/blob/main/dev/lis-trait-search-element.html
> 
> and we do seem to have GlycineMine hanging on a search on "flower". So I'll continue to investigate. This is also true in Apollo Sandbox. There is definitely something crashy going on, and the mine throws `java.lang.IllegalArgumentException: Cannot find a query` but eventually recovers.
> 
> Continuing research....

SCRATCH THAT it's working fine. I think I collided against GlycineMine stuttering from some other query. This component and its implementation under /dev works fine.

**Comment by sammyjava** [comment]
As far as I can tell, there's nothing to fix, @That-Thing  - let me know if you have a reproducible, conformant-input crash that I should be able to reproduce.

**Comment by That-Thing** [comment]
It's still crashing for me with even with page set to 1 and name removed.

**Comment by sammyjava** [comment]
Are you using Apollo Sandbox to test it? Can you confirm that this query is working? If not, there's something odd going on with your setup.

**Operation**
```
query Query($pageSize: Int, $page: Int, $name: String) {
  traits(pageSize: $pageSize, page: $page, name: $name) {
    results {
      id
      identifier
      name
      description
    }
  }
}
```

**Variables**
```
{
  "page": 1,
  "pageSize": 10,
  "name": "flower",
}
```

**Comment by sammyjava** [comment]
That works fine with the following .env:
```
PORT=4444
INTERMINE_URI=https://mines.legumeinfo.org/glycinemine/service
MICROSERVICES_URI=https://services.lis.ncgr.org
```

**Comment by sammyjava** [comment]
![Screenshot 2023-09-15 at 11-36-21 Apollo Server](https://github.com/legumeinfo/graphql-server/assets/5657219/4c70af4c-22f0-4f79-8714-43aec8152ace)

**Comment by That-Thing** [comment]
Odd. The query you sent works fine,

**Comment by sammyjava** [comment]
Ah, good. Add direct result types one by one (not derivative types like publication.title) until it crashes, if it does. Then, if it doesn't crash, start adding derivative types one by one. There is probably a bug in here, but we need to find it.

**Comment by That-Thing** [comment]
It seems it crashes when name is missing or set to *, my initial query works fine when specifying a name.

**Comment by sammyjava** [comment]
OK, let me look into that, leave off querying until I get back to you so I've got a running GlycineMine. :)

**Comment by sammyjava** [comment]
Um, this query does not supply name and runs fine. Does it not run for you? (Go ahead and try it.)
```
query Query($pageSize: Int, $page: Int) {
  traits(pageSize: $pageSize, page: $page) {
    results {
      id
      identifier
      description
      name
    }
  }
}
```

**Comment by That-Thing** [comment]
That's very weird, that query runs fine for me as well, but the query I posted earlier results in a crash when no name is provided.

**Comment by sammyjava** [comment]
Then I think you have to start with this query and slowly add more and more result types until you reproduce the crash. Then we'll have a minimal crashing exemplar for me to debug.

**Comment by That-Thing** [comment]
From what I can tell, the mine crashes every time something that has children is requested (ex: GWAS, qtlStudt, ontologyAnnotations)

**Comment by sammyjava** [comment]
Not all, but got it, thanks. Here's the error if I include GWASResults.identifier:
```json
          "body": {
            "results": [],
            "executionTime": "2023.09.20 10:21::37",
            "wasSuccessful": false,
            "error": "XML is well formatted but query contains errors:\nPath GWASResult.identifier in view list is not in the model.\n",
            "statusCode": 400
          }
```
GWASResult doesn't have an identifier - not sure how that snuck in. I'll check this and other types that may have a similar issue.

**Comment by alancleary** [comment]
@sammyjava Has this been resolved?

**Comment by sammyjava** [comment]
Yup!
