### ISSUE TITLE
Need support for OUTER JOIN path queries in intermine.server.ts

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/graphql-server#87]
Being able to query on genus or species in the trait search web component without specifying whether it's a GWAS or QTLStudy means that we have to be able to implement an OUTER JOIN query to avoid always getting an empty response. (Trait.gwas and Trait.qtlStudy are mutually exclusive.) This is something we'll want in the future for other queries as well, these are pretty common mine queries.

Here's what it looks like in PathQuery:

**genus (Phaseolus) supplied:**
```xml
<query name="" model="genomic" view="Trait.primaryIdentifier" longDescription="" sortOrder="Trait.primaryIdentifier asc" constraintLogic="A and B">
   <join path="Trait.gwas" style="OUTER"/>
   <join path="Trait.qtlStudy" style="OUTER"/>
   <constraint path="Trait.qtlStudy.organism.genus" code="A" op="=" value="Phaseolus"/>
   <constraint path="Trait.gwas.organism.genus" code="B" op="=" value="Phaseolus"/>
</query>
```

**species (vulgaris) supplied:**
```xml
<query name="" model="genomic" view="Trait.primaryIdentifier" longDescription="" sortOrder="Trait.primaryIdentifier asc" constraintLogic="A and B">
   <join path="Trait.qtls" style="OUTER"/>
   <join path="Trait.gwas" style="OUTER"/>
   <constraint path="Trait.gwas.organism.species" code="A" op="=" value="vulgaris"/>
   <constraint path="Trait.qtls.qtlStudy.organism.species" code="B" op="=" value="vulgaris"/>
</query>
```

This strikes me as being somewhat difficult, so I'll throw it at you, @alancleary .

**Comment by sammyjava** [comment]
Although if it's as simple as the following, let me know and I'll give it a try:
```javascript
// creates a Path Query OUTER JOIN XML string
export const intermineOuterJoin =
    (path: string): string => {
        return `<join path='${path}' style='OUTER'/>`;
    };

// creates a Path Query OUTER JOIN XML string
export const intermineOuterJoinPathQuery =
    (viewAttributes: Array<string>, sortBy: string, joins: Array<string>=[], constraints: Array<string>=[]): string => {
        const view = viewAttributes.join(' ');
        const join = joins.join('');
        const constraint = constraints.join('');
        return `<query model='genomic' view='${view}' sortOrder='${sortBy}'>${join} ${constraint}</query>`;
    };
```

**Comment by alancleary** [comment]
> Although if it's as simple as the following, let me know and I'll give it a try:
> 
> ```js
> // creates a Path Query OUTER JOIN XML string
> export const intermineOuterJoin =
>     (path: string): string => {
>         return `<join path='${path}' style='OUTER'/>`;
>     };
> 
> // creates a Path Query OUTER JOIN XML string
> export const intermineOuterJoinPathQuery =
>     (viewAttributes: Array<string>, sortBy: string, joins: Array<string>=[], constraints: Array<string>=[]): string => {
>         const view = viewAttributes.join(' ');
>         const join = joins.join('');
>         const constraint = constraints.join('');
>         return `<query model='genomic' view='${view}' sortOrder='${sortBy}'>${join} ${constraint}</query>`;
>     };
> ```

I would make it a little more generic, but that's pretty close:

1. Change `intermineOuterJoin` to just `intermineJoin` and make the style a parameter
2. Add an optional `code` parameter to the `intermineConstraint` method
3. Extend the existing `interminePathQuery` method instead of introducing a new `intermineOuterJoinPathQuery` method
    3.1. Pass joins in via the `constrains` parameter (no change necessary)
    3.2. Add an optional `constraintLogic` parameter

Regarding constraint logic, is it possible to define multiple constraints for a single path query? If so, the `constraintLogic` parameter should be an Array and the appropriate string join should be applied when constructing the path query, like how the `viewAttributes` and `constraints` parameters are being handled.

**Comment by sammyjava** [comment]
How about you do it, which will take vastly less time, since you've now spec'd it. :)

Joins are not constraints so IMO they should not be passed in via the constraints parameter. They are an entirely different XML entity even if they fit inside the `<query></query>` tag. `<join/>` is at the same XML level as `<constraint/>`. But that's my opinion, I get that you can glom them together to get the job done.

I don't understand your question about multiple constraints. We have them all the time. I guess I don't know what you mean by `constraintLogic` unless you mean whether the joins are inner or outer. The working examples above each have two outer joins and two constraints.

Keep in mind that INNER JOIN is the default. You only need to specify OUTER JOIN in path queries.

Whatever you implement that works will be fine with me. :)

**Comment by alancleary** [comment]
OK, I can implement it. 

Regarding multiple constrains, I think I should've said multiple constraint logics. Looking at the Intermine Query Builder documentation, it seems like this should probably be a magic string given as a parameter to the `interminePathQuery` method since the logic can be arbitrarily complex, i.e. you can have many fields constraining a single join and/or logic for multiple joins.

Here's an example that constrains the Trait outer join by both genus and species:
```xml
<query name="" model="genomic" view="Trait.primaryIdentifier" longDescription="" sortOrder="Trait.primaryIdentifier asc" constraintLogic="A and B and C and D">
    <join path="Trait.gwas" style="OUTER"/>
    <join path="Trait.qtlStudy" style="OUTER"/>
    <constraint path="Trait.qtlStudy.organism.genus" code="A" op="=" value="Phaseolus"/>
    <constraint path="Trait.gwas.organism.genus" code="B" op="=" value="Phaseolus"/>
    <constraint path="Trait.qtls.qtlStudy.organism.species" code="C" op="=" value="vulgaris"/>
    <constraint path="Trait.gwas.organism.species" code="D" op="=" value="vulgaris"/>
</query>
```
Or am I misunderstanding how such a path query would be structured?

**Comment by sammyjava** [comment]
No, that's correct, The "constraintLogic" in a path query is a single string tying the "A, B, C, D, ..." labeled constraints with "AND" or "OR".  There's even a little query builder tool for editing that string:
![image](https://github.com/legumeinfo/graphql-server/assets/5657219/cc564879-1757-47f4-94b4-5e8f3caa4d61)

**Comment by alancleary** [comment]
OK, thanks for clarifying. In that case I'll just make the `constraintLogic` parameter a magic string.

In the example you posted you put `A and C, B and D` in the constraint logic input, but the query you posted has `A and B and D and C`. Are these equivalent?

**Comment by sammyjava** [comment]
> OK, thanks for clarifying. In that case I'll just make the `constraintLogic` parameter a magic string.
> 
> In the example you posted you put `A and C, B and D` in the constraint logic input, but the query you posted has `A and B and D and C`. Are these equivalent?

Yes. The Path Query web tool likes to separate the related parts by a comma, but the actual query uses "and". Even if you import the query from XML (I just checked) it displays the constraintLogic with a comma. (There is no comma in SQL constraint logic and the XML path query is based on SQL.) Kinda weird UI, actually.

**Comment by sammyjava** [comment]
This appears to test correctly. Unfortunately (sort of) the OUTER JOIN was not actually what I want, because it ends up returning ALL traits (those without QTLStudy and those without GWAS). But we need this, anyway, so it's a good addition. I'll look into ways of effectively doing this SQL query via path query:
```sql
(SELECT trait.name,qtlstudy.primaryidentifier,qtlstudy.organismid FROM trait,qtlstudy WHERE trait.qtlstudyid=qtlstudy.id AND qtlstudy.organismid=37000002)
UNION
(SELECT trait.name,gwas.primaryidentifier,gwas.organismid FROM trait,gwas WHERE trait.gwasid=gwas.id AND gwas.organismid=37000002)

**Comment by sammyjava** [comment]
I say we close this and merge this into main. I did test it, and confirm that it generating correct path query code and working, which is why I realized I was mistaken about needing it. :)
