### ISSUE TITLE
Upgrade to Apollo Server v4

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/graphql-server#9]
Apollo Server v4 has been released and v3 will be EOL in October 2023. This is a big upgrade with breaking changes so better to do it now before this code goes into production!

Speaking of big upgrades; looking at the [Get started with Apollo Server](https://www.apollographql.com/docs/apollo-server/getting-started) tutorial in the Apollo docs, they recommend using TypeScript. I don't remember why we opted to use JavaScript in the first place but I'm thinking we should use this upgrade as an opportunity to switch to TypeScript, if only to make our code more verbose. For example, we could [generate types from our schema](https://www.apollographql.com/docs/apollo-server/workflow/generate-types/) (among many other things), which would really put our code in line with the API.

I know @sammyjava might have opinions on this. I'd like to hear what him and anyone else I assigned to this issue thinks.

**Comment by adf-ncgr** [comment]
I'm in favor; type safety FTW!

**Comment by sammyjava** [comment]
FIne with me. I've been typing scads of lines of JS the past couple of days, but converting to TS should be a healthy exercise. Let me get my mine-based schema branch up to a certain level (useful set of objects and their dependencies) and I'll clone to a new v4 branch to work on that project. I agree, it'll be October before we know it and as I mentioned to Alan, there is some fancy "incremental delivery" aspect in v4 (still experimental) that maybe useful to us.

https://www.apollographql.com/docs/apollo-server/workflow/requests#incremental-delivery-experimental

**Comment by alancleary** [comment]
FYI I'm going to take care of this today. The code is growing rapidly and we're rapidly moving towards production.

**Comment by sammyjava** [comment]
Yikes that seems like a massive job. Glad it's you and not me!

**Comment by alancleary** [comment]
An initial conversion from JavaScript to TypeScript was done in commit f2736dda914f857d12f9a46d10e2627c90bb57ca, which is currently in the "typescript" branch.

Now I'm going to make the type checking a bit more stringent and do another pass to add types to everything.

**Comment by alancleary** [comment]
Commit 4f6ec86f5a8e9506a3443fa33819db8b9aafe286 added `noUnusedLocals` to `tsconfig.json`. And commit 926e153fca7dd78646afd1dc573bdea96ed90782 added `noUnusedParameters`. @sammyjava The latter required removing pagination from a handful or resolvers and data source methods because the data source methods weren't actually using those parameters. Do we want to implement pagination for those methods? I wasn't sure so I left in the original code as comments.

**Comment by sammyjava** [comment]
Probably not, those are queries that return one or very few results by nature. Like Gene.locations returns a single result from an LIS mine because we define a "Gene" to be a unique object from a single annotation. But other mines call a Gene that which has symbol "TT8" with locations on many genomes, so locations is a collection, not reference.

**Comment by alancleary** [comment]
OK. I'll remove the commented code blocks then. Thanks!

**Comment by alancleary** [comment]
Commit b93bb214e0e2b359dcc79ca6e802983758245ea1 added `noImplicitReturns`, commit 5a4b9b5c139e1ab331b251c30096bd3ac67d07dc added `noFallthroughCasesInSwitch`, and commit 766c0bd2e243a3f71ce479b9cab729d398b5a293 add `noImplicitOverride`.

The only other options I was going to add to `tsconfig.json` were `noImplicitAny` and `noImplicitThis`. These are going to require adding A LOT of types. I'm going to start working on it but I think the thing to do is chip away at it over time, i.e. the options will be added to the config but the errors will be largely ignored using the `@ts-ignore` and `@ts-nocheck` comments.

**Comment by alancleary** [comment]
Commit ed74a09b814876cf69fc4468025af6450d240dc0 added `noImplicitAny` to `tsconfig.json`. This only require 1 use of `@ts-nocheck`, so I think things are in a pretty good place.

@sammyjava I ended up commenting out the [`consolidate` function](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/intermine.pathquery.js#L33) we discussed. This is because I could not find a code path from a resolver that would actually trigger the consolidation code in the function. It appears to be a vestige of when the `proteinDomains` field of the gene or gene family models was populate directly from a gene or gene family pathquery. However, all fields that are a nested type are now handled via [resolver chaining](https://github.com/legumeinfo/graphql-server/blob/main/src/resolvers/intermine/gene.js#L38), meaning no Intermine response should have duplicates due to a nested field. Can you confirm that this is correct?

**Comment by adf-ncgr** [comment]
FWIW I think that consolidate function may be a vestige of something I had done long ago. Feel free to remove it if it isn't serving any purpose.

**Comment by alancleary** [comment]
OK. Thanks for clarifying @adf-ncgr. We'll see if @sammyjava knows something we don't.

**Comment by alancleary** [comment]
Commit 029a016a0b3c634fa53cdfac2abf98e197b9c1d3 updated the Intermine data source to use the same cache as the server. I was basically just following the Apollo Server v4 code example here but I guess the advantage is if we ever use something fancy like Redis for caching the server then the Intermine data source will automatically do the same.

**Comment by alancleary** [comment]
Commit abc95e2b50a65bd5adbead22757485c8a01409eb updated the resolvers to use underscores for unused parameter variables. This has no functional purpose; it's just to follow the conventions of Apollo.

**Comment by alancleary** [comment]
Commit 9519640930cc6d062b339a48973bf0497716d564 added explicit development and production modes.

**Comment by alancleary** [comment]
OK, thanks for clarifying.

> Ship it. Or move it more toward shipping.

I'm updating the Docker stuff now and then I'll open a PR into main. @sammyjava Mind being the reviewer on the PR?

**Comment by sammyjava** [comment]
Happy to be. Not sure I'll use as fine a tooth comb as you do, but I'll give 'er a good going over.

**Comment by alancleary** [comment]
> Happy to be. Not sure I'll use as fine a tooth comb as you do, but I'll give 'er a good going over.

No need to be too meticulous. I mostly want to be sure that the code is functionally the same. If only we had automated tests... I'm also interested in your thoughts on the updated npm scripts and Docker Compose stuff. I had to rewrite the npm scripts because TypeScript uses different tooling but I tried to make them similar in spirit to what you already had in place.

**Comment by alancleary** [comment]
Commit 1e49d93b7ae3b148a0defcb4f0f9320ee24b0724 updated the `Dockerfile` to more easily support both development and production modes.

Commit 820ccf47f2d52b23f5b401bb8dfb076eb6efd09e added Docker Compose files. This also added a healthcheck to the `Dockerfile` so Docker Compose can determine if the server is healthy in production.

Commit 9f682b931ffdc6b309ec923cec6b6784b77baa2c added a `.env` file to allow the server to be easily configured when running both locally and via Docker Compose.

**Comment by alancleary** [comment]
Commit 1e85131b6dc3c431bede03575b20f491c5a4e0de removed the deprecated `consolidate` function we discussed.

**Comment by alancleary** [comment]
Commits 5e828c6a5968261136629bc56df5c06fd017fb78 and b2c7118dee626c3556f299c5fcf95104f99ec30b updated the adding a search query documentation.

**Comment by alancleary** [comment]
Commit f9ecceabd5dba2438cb7c8fa8261aa721c496a94 updated the file structure readme.

**Comment by sammyjava** [comment]
This is done, correct?

**Comment by alancleary** [comment]
Yes! I forgot to close it. Thanks for the nudge.
